# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
my_rand_unif <- function() {
    .Call(`_lvmcomp2_my_rand_unif`)
}

#' @export
obj_func_cpp <- function(sigma, sigma_hat) {
    .Call(`_lvmcomp2_obj_func_cpp`, sigma, sigma_hat)
}

#' @export
calcu_sigma_cmle_cpp <- function(theta, tol) {
    .Call(`_lvmcomp2_calcu_sigma_cmle_cpp`, theta, tol)
}

#' @export
log_sum_exp2 <- function(tmp) {
    .Call(`_lvmcomp2_log_sum_exp2`, tmp)
}

#' @export
update_sigma_one_step2 <- function(theta0, B0, B_res1, B_res2, B_mis_info, mcn, alpha, step, c1, c2) {
    .Call(`_lvmcomp2_update_sigma_one_step2`, theta0, B0, B_res1, B_res2, B_mis_info, mcn, alpha, step, c1, c2)
}

#' @export
calcu_sigma_cmle_cpp1 <- function(theta) {
    .Call(`_lvmcomp2_calcu_sigma_cmle_cpp1`, theta)
}

#' @export
test_deriv <- function(B0, theta0) {
    .Call(`_lvmcomp2_test_deriv`, B0, theta0)
}

#' @export
oakes <- function(theta0, response, Q, Sigma, A, d, M = 400L) {
    .Call(`_lvmcomp2_oakes`, theta0, response, Q, Sigma, A, d, M)
}

#' @export
obj_det <- function(theta, B) {
    .Call(`_lvmcomp2_obj_det`, theta, B)
}

#' @export
bfgs_update <- function(theta0, B0, flag, tol = 1e-4) {
    .Call(`_lvmcomp2_bfgs_update`, theta0, B0, flag, tol)
}

neg_loglik_logi_partial_credit <- function(theta, response_j, A_j, D_j) {
    .Call(`_lvmcomp2_neg_loglik_logi_partial_credit`, theta, response_j, A_j, D_j)
}

neg_loglik_deri_partial_credit <- function(theta, response_j, A_j, D_j) {
    .Call(`_lvmcomp2_neg_loglik_deri_partial_credit`, theta, response_j, A_j, D_j)
}

my_Logistic_cpp <- function(XX, YY, beta0, d0) {
    .Call(`_lvmcomp2_my_Logistic_cpp`, XX, YY, beta0, d0)
}

my_Logistic_cpp_partial <- function(XX, YY, beta0, D0) {
    .Call(`_lvmcomp2_my_Logistic_cpp_partial`, XX, YY, beta0, D0)
}

#' @export
stem_mirtc <- function(response, Q, A0, d0, theta0, sigma0, T, parallel) {
    .Call(`_lvmcomp2_stem_mirtc`, response, Q, A0, d0, theta0, sigma0, T, parallel)
}

stem_pcirtc <- function(response, Q, A0, D0, theta0, sigma0, T, parallel) {
    .Call(`_lvmcomp2_stem_pcirtc`, response, Q, A0, D0, theta0, sigma0, T, parallel)
}

#' @export
stem_simu <- function(response, Q, A0, d0, B0, theta0, ave_from = 100L, max_steps = 200L, print_proc = TRUE) {
    .Call(`_lvmcomp2_stem_simu`, response, Q, A0, d0, B0, theta0, ave_from, max_steps, print_proc)
}

#' @export
sa_penmirt <- function(response, theta, A, d, B, lambda, zero, anchor, alpha, step = 1, max_steps = 200L) {
    .Call(`_lvmcomp2_sa_penmirt`, response, theta, A, d, B, lambda, zero, anchor, alpha, step, max_steps)
}

#' @export
sa_penmirt1 <- function(response, theta, A, d, B, lambda, zero, anchor, alpha, step = 1, ave_from = 50L, max_steps = 200L, tol = 0.01) {
    .Call(`_lvmcomp2_sa_penmirt1`, response, theta, A, d, B, lambda, zero, anchor, alpha, step, ave_from, max_steps, tol)
}

#' @export
sa_mirt_conf <- function(response, A, Q, d, B, theta, alpha, step = 1.0, ave_from = 100L, max_steps = 200L) {
    .Call(`_lvmcomp2_sa_mirt_conf`, response, A, Q, d, B, theta, alpha, step, ave_from, max_steps)
}

#' @export
sa_mirt_conf_no_ave <- function(response, A, Q, d, B, theta, alpha, step = 1.0, max_steps = 200L) {
    .Call(`_lvmcomp2_sa_mirt_conf_no_ave`, response, A, Q, d, B, theta, alpha, step, max_steps)
}

#' @export
MHRM_conf <- function(response, A, Q, d, B, theta, step = 1.0, max_steps = 200L) {
    .Call(`_lvmcomp2_MHRM_conf`, response, A, Q, d, B, theta, step, max_steps)
}

#' @export
sa_mirt_conf1 <- function(response, A, Q, d, B, theta, alpha, step = 1.0, ave_from = 100L, max_steps = 200L) {
    .Call(`_lvmcomp2_sa_mirt_conf1`, response, A, Q, d, B, theta, alpha, step, ave_from, max_steps)
}

#' @export
sa_mirt_arma <- function(response, Q, A0, d0, theta0, A_true, d_true, alpha, C0, window_size = 100L, block_size = 20L, max_steps = 2000L, print_proc = FALSE) {
    .Call(`_lvmcomp2_sa_mirt_arma`, response, Q, A0, d0, theta0, A_true, d_true, alpha, C0, window_size, block_size, max_steps, print_proc)
}

#' @export
stem_init <- function(response, Q, A0, d0, theta0, max_steps, window_size = 40L, block_size = 20L, tol = 0.05) {
    .Call(`_lvmcomp2_stem_init`, response, Q, A0, d0, theta0, max_steps, window_size, block_size, tol)
}

